import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const renderer = readFileSync(new URL('./src/threeGroundRenderer.mjs', import.meta.url), 'utf8');
const visualStyle = readFileSync(new URL('./src/threeGroundVisualStyle.mjs', import.meta.url), 'utf8');
const materialAssets = readFileSync(new URL('./src/groundMaterialAssets.mjs', import.meta.url), 'utf8');
const postProcessing = readFileSync(new URL('./src/threeGroundPostProcessing.mjs', import.meta.url), 'utf8');
const adapter = readFileSync(new URL('./src/preview1Renderer.mjs', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));

assert.equal(packageJson.dependencies.three, '0.185.0', 'Three.js version must be pinned');
assert.match(renderer, /from 'three\/webgpu'/, 'ground renderer must use the Three WebGPU-capable build');
assert.match(renderer, /new THREE\.WebGPURenderer/, 'ground renderer must instantiate Three WebGPURenderer');
assert.match(renderer, /forceWebGL/, 'ground renderer must retain an explicit WebGL2 fallback\/baseline path');
assert.match(renderer, /new THREE\.BufferGeometry/, 'verified terrain buffers must become Three BufferGeometry');
assert.match(renderer, /geometry\.setAttribute\('normal'/, 'worker-provided terrain normals must reach Three geometry');
assert.match(renderer, /geometry\.setAttribute\('uv'/, 'worker-provided terrain UVs must reach Three geometry');
assert.match(renderer, /geometry\.setAttribute\('color'/, 'renderer-only macro variation must use a dedicated vertex color attribute');
assert.match(renderer, /createGroundMaterialLibrary/, 'renderer must load the pinned local material catalog');
assert.match(materialAssets, /new THREE\.MeshStandardMaterial/, 'ground renderer must use a lit PBR material path');
assert.match(materialAssets, /roughnessMap:/, 'surfaces must carry measured roughness variation');
assert.match(materialAssets, /normalMap:/, 'quality profiles must support tangent-space normal maps');
assert.match(materialAssets, /THREE\.RepeatWrapping/, 'meter-scaled PBR textures must tile instead of stretch');
assert.match(materialAssets, /same-origin-local-assets-only/, 'runtime materials must stay on the local static-asset boundary');
assert.match(materialAssets, /vertexColors:\s*options\.vertexColors/, 'terrain material must consume renderer-only macro variation');
assert.match(renderer, /geometry_displacement:\s*false/, 'terrain styling must explicitly preserve accepted DTM geometry');
assert.doesNotMatch(renderer, /displacementMap\s*:/, 'renderer must not visually displace accepted DTM geometry');
assert.match(renderer, /resolvedWallMaterial/, 'source-backed building walls must have a dedicated material class');
assert.match(renderer, /resolvedRoofMaterial/, 'source-backed building roofs must have a dedicated material class');
assert.match(renderer, /fallbackWallMaterial/, 'fallback-height building walls must remain visually distinct');
assert.match(renderer, /fallbackRoofMaterial/, 'fallback-height building roofs must remain visually distinct');
assert.match(renderer, /building_materials:\s*\{/, 'runtime stats must expose building material semantics');
assert.match(renderer, /draw_calls_per_frame:\s*colorDrawCalls/, 'draw-call stats must keep color-pass estimate explicit when shadows add work');
assert.match(renderer, /shadow_draw_candidates:\s*shadowDrawCandidates/, 'shadow pass cost must be visible in runtime stats');
assert.match(renderer, /draw_call_semantics:/, 'draw-call stats must explain shadow-pass semantics');
assert.match(renderer, /camera\.position\.set\(0, centerGround \+ 1\.7, 14\)/, 'camera must start at human eye height over sampled ground');
assert.match(renderer, /renderer_adapter:\s*'three-ground\/0\.2'/, 'runtime stats must identify the enhanced Three renderer adapter');
assert.match(renderer, /terrain_material:\s*\{/, 'runtime stats must expose terrain material evidence');
assert.match(renderer, /renderer_visual_style:/, 'runtime stats must expose visual style/shadow evidence');
assert.match(renderer, /lighting\.updateAnchor\(\[\.\.\.pose\.position\]\)/, 'bounded sun/shadow anchor must follow the derived character pose');
assert.match(renderer, /configureObjectShadowRole\(humanoid\.root/, 'humanoid must participate in the bounded shadow pass');
assert.match(renderer, /getVisualStyle/, 'renderer must expose the active visual style for browser acceptance');
assert.match(renderer, /getTerrainResourceLifecycle/, 'adapter must preserve terrain resource lifecycle integration');
assert.match(renderer, /sceneGeometry\.roads\.uvs/, 'road PBR material must consume the existing meter-scaled road UVs');
assert.match(renderer, /buildingsResolved\.walls\.uvs/, 'building PBR material must consume wall UVs');
assert.match(renderer, /createGroundPostProcessing/, 'renderer must expose profile-gated post processing');
assert.match(postProcessing, /GTAONode/, 'high profiles must use WebGPU-capable GTAO');
assert.match(postProcessing, /BloomNode/, 'high profiles must use restrained HDR bloom');
assert.match(visualStyle, /ACESFilmicToneMapping/, 'visual pass must use explicit ACES filmic tone mapping');
assert.match(visualStyle, /SRGBColorSpace/, 'visual pass must use explicit sRGB output color space');
assert.match(visualStyle, /shadowHalfExtentM:\s*70/, 'shadow frustum must stay bounded instead of covering the whole tile');
assert.match(visualStyle, /shadowMapSize:\s*1024/, 'shadow map budget must be explicit');
assert.match(adapter, /createThreeGroundRenderer/, 'Preview 1 renderer boundary must route through Three.js');
assert.doesNotMatch(renderer, /kartverket|nvdb|overpass|openstreetmap/i, 'renderer must not gain raw-source knowledge');

console.log('THREE_GROUND_RENDERER_STRUCTURE_PASS');
