export const GRAPHICS_PROFILE_IDS = Object.freeze(['low', 'balanced', 'high', 'ultra']);
export const RENDERER_PREFERENCES = Object.freeze(['auto', 'webgpu', 'webgl2']);

const PROFILES = Object.freeze({
  low: Object.freeze({
    id: 'low',
    label: 'Lav',
    terrainOutputSize: 65,
    maxDpr: 1,
    msaaSamples: 1,
    webglAntialias: false,
    powerPreference: 'low-power',
    vegetationBudget: 2500,
    textureAnisotropy: 2,
    normalMaps: false,
    shadowMapSize: 512,
    shadowFilter: 'basic',
    shadowHalfExtentM: 55,
    shadowAnchorUpdateDistanceM: 12,
    fogNearM: 130,
    fogFarM: 900,
    cameraFarM: 1800,
    toneMappingExposure: 1,
    hemisphereIntensity: 1.1,
    sunIntensity: 2.7,
    ambientOcclusion: false,
    bloom: false,
  }),
  balanced: Object.freeze({
    id: 'balanced',
    label: 'Balansert',
    terrainOutputSize: 129,
    maxDpr: 1.5,
    msaaSamples: 1,
    webglAntialias: true,
    powerPreference: undefined,
    vegetationBudget: 7500,
    textureAnisotropy: 4,
    normalMaps: true,
    shadowMapSize: 1024,
    shadowFilter: 'basic',
    shadowHalfExtentM: 70,
    shadowAnchorUpdateDistanceM: 8,
    fogNearM: 180,
    fogFarM: 1300,
    cameraFarM: 2400,
    toneMappingExposure: 1.04,
    hemisphereIntensity: 1.2,
    sunIntensity: 3,
    ambientOcclusion: false,
    bloom: false,
  }),
  high: Object.freeze({
    id: 'high',
    label: 'Høy',
    terrainOutputSize: 257,
    maxDpr: 2,
    msaaSamples: 4,
    webglAntialias: true,
    powerPreference: 'high-performance',
    vegetationBudget: 20000,
    textureAnisotropy: 8,
    normalMaps: true,
    shadowMapSize: 2048,
    shadowFilter: 'pcf',
    shadowHalfExtentM: 85,
    shadowAnchorUpdateDistanceM: 5,
    fogNearM: 220,
    fogFarM: 1800,
    cameraFarM: 3200,
    toneMappingExposure: 1.08,
    hemisphereIntensity: 1.22,
    sunIntensity: 3.2,
    ambientOcclusion: true,
    ambientOcclusionResolutionScale: 0.5,
    ambientOcclusionSamples: 8,
    ambientOcclusionRadius: 0.32,
    ambientOcclusionDistanceFallOff: 0.72,
    ambientOcclusionStrength: 0.3,
    bloom: true,
    bloomStrength: 0.055,
    bloomRadius: 0.16,
    bloomThreshold: 1.1,
  }),
  ultra: Object.freeze({
    id: 'ultra',
    label: 'Ultra',
    terrainOutputSize: 513,
    maxDpr: 2.5,
    msaaSamples: 4,
    webglAntialias: true,
    powerPreference: 'high-performance',
    vegetationBudget: 40000,
    textureAnisotropy: 16,
    normalMaps: true,
    shadowMapSize: 4096,
    shadowFilter: 'pcf',
    shadowHalfExtentM: 110,
    shadowAnchorUpdateDistanceM: 3,
    fogNearM: 260,
    fogFarM: 2300,
    cameraFarM: 4200,
    toneMappingExposure: 1.1,
    hemisphereIntensity: 1.24,
    sunIntensity: 3.3,
    ambientOcclusion: true,
    ambientOcclusionResolutionScale: 0.75,
    ambientOcclusionSamples: 16,
    ambientOcclusionRadius: 0.35,
    ambientOcclusionDistanceFallOff: 0.68,
    ambientOcclusionStrength: 0.36,
    bloom: true,
    bloomStrength: 0.065,
    bloomRadius: 0.2,
    bloomThreshold: 1.08,
  }),
});

export function resolveGraphicsProfile(value = 'balanced') {
  const id = GRAPHICS_PROFILE_IDS.includes(value) ? value : 'balanced';
  return PROFILES[id];
}

export function resolveRendererPreference(value = 'auto') {
  return RENDERER_PREFERENCES.includes(value) ? value : 'auto';
}
