export function createPreview1Renderer(options: any): Promise<{
  header: any;
  firstFrame: Promise<{
    at: number;
    drawGapMs: number | null;
    drawCpuMs: number;
    drawCalls: number;
    backend: 'webgpu' | 'webgl2';
    pixelRatio: number;
    camera: { yaw: number; pitch: number; distance: number; target?: number[] };
    character?: HumanoidRenderState;
  }>;
  stats: {
    terrain_vertices: number;
    terrain_triangles: number;
    road_paths: number;
    road_surface_paths: number;
    road_surface_segments: number;
    road_surface_triangles: number;
    road_width_semantics: 'renderer-only-fallback' | string;
    road_surface_lift_m: number;
    building_footprints: number;
    source_backed_building_heights: number;
    unresolved_building_heights: number;
    building_resolved_height_semantics: 'source-backed' | string;
    building_fallback_height_semantics: 'renderer-only-fallback' | string;
    building_wall_triangles: number;
    building_roof_triangles: number;
    building_roof_triangulation: string;
    debug_road_width_m: number;
    debug_unresolved_building_height_m: number;
    renderer_adapter?: string;
    backend: 'webgpu' | 'webgl2';
    graphics_profile: 'low' | 'balanced' | 'high' | string;
    max_dpr: number;
    pixel_ratio: number;
    msaa_samples: number | null;
    power_preference?: string;
    draw_calls_per_frame: number;
    draw_call_semantics?: string;
    shadow_draw_candidates?: number;
    gpu_buffer_count: number;
    gpu_buffer_payload_bytes: number;
    gpu_attachment_estimated_bytes?: number;
    gpu_texture_payload_bytes?: number;
    timestamp_query_supported: boolean;
    camera_eye_height_m?: number;
    camera_mode?: string;
    character?: HumanoidRenderState;
    building_materials?: any;
    renderer_visual_style?: GroundVisualStyleState;
    timing_ms: any;
  };
  invalidate(): void;
  dispose(): void;
  setCharacterAnimationState(state: 'idle' | 'walk', options?: { fadeSeconds?: number }): HumanoidRenderState;
  setCharacterRenderPose(pose: { entityId?: string; worldFrameId?: string; originSeriesId?: string; originEpoch?: number; position: Float32Array; headingRadians: number }): HumanoidRenderState;
  getCharacterState(): HumanoidRenderState;
  getCameraState(): { yaw: number; pitch: number; distance: number; target: number[] };
  getVisualStyle(): GroundVisualStyleState;
}>;

type GroundVisualStyleState = {
  schema: 'nwe.ground-visual-style/0.1' | string;
  tone_mapping: 'ACESFilmicToneMapping' | string;
  tone_mapping_exposure: number;
  output_color_space: 'SRGBColorSpace' | string;
  shadows_enabled: boolean;
  sky: { color: number; fog_near_m: number; fog_far_m: number };
  sun: {
    type: string;
    intensity: number;
    cast_shadow: boolean;
    requested_anchor: readonly number[];
    anchor: readonly number[];
    offset: readonly number[];
  };
  shadow: {
    strategy: 'single-player-following-directional-frustum' | string;
    map_size: number;
    half_extent_m: number;
    near_m: number;
    far_m: number;
    bias: number;
    normal_bias: number;
    intensity: number;
    auto_update: boolean;
    update_distance_m: number;
    update_count: number;
  };
};

type HumanoidRenderState = {
  schema: 'nwe.humanoid-render-state/0.1' | string;
  asset_id: string;
  source_commit: string;
  source_git_blob_sha1: string;
  source_byte_size: number;
  license: string;
  source_request_url: string;
  source_request_origin: string;
  runtime_dependency: 'commit-pinned-renderer-asset' | string;
  state: 'idle' | 'walk';
  idle_clip: string;
  walk_clip: string;
  render_mesh_count: number;
  normalized_height_m: number;
  renderer_only_spawn: true;
  animation_state_probe: any;
  render_pose?: { entity_id: string | null; world_frame_id: string | null; origin_series_id: string | null; origin_epoch: number | null; position: readonly number[]; heading_radians: number; model_forward_yaw_offset: number } | null;
};
