export function createPreview1Renderer(options: any): Promise<{
  header: any;
  firstFrame: Promise<{
    at: number;
    drawGapMs: number | null;
    drawCpuMs: number;
    drawCalls: number;
    backend: 'webgpu' | 'webgl2';
    pixelRatio: number;
    camera: { yaw: number; pitch: number; distance: number };
  }>;
  stats: {
    terrain_vertices: number;
    terrain_triangles: number;
    road_paths: number;
    road_surface_paths: number;
    road_surface_segments: number;
    road_surface_triangles: number;
    road_width_semantics: 'renderer-only-fallback' | string;
    road_surface_lift_m: number;
    building_footprints: number;
    source_backed_building_heights: number;
    unresolved_building_heights: number;
    building_resolved_height_semantics: 'source-backed' | string;
    building_fallback_height_semantics: 'renderer-only-fallback' | string;
    building_wall_triangles: number;
    building_roof_triangles: number;
    building_roof_triangulation: string;
    debug_road_width_m: number;
    debug_unresolved_building_height_m: number;
    renderer_adapter?: string;
    backend: 'webgpu' | 'webgl2';
    graphics_profile: 'low' | 'balanced' | 'high' | string;
    max_dpr: number;
    pixel_ratio: number;
    msaa_samples: number | null;
    power_preference?: string;
    draw_calls_per_frame: number;
    gpu_buffer_count: number;
    gpu_buffer_payload_bytes: number;
    gpu_attachment_estimated_bytes?: number;
    gpu_texture_payload_bytes?: number;
    timestamp_query_supported: boolean;
    camera_eye_height_m?: number;
    building_materials?: {
      schema: string;
      source_backed: { wall: string; roof: string };
      unresolved: { wall: string; roof: string };
      height_semantics: { source_backed: string; unresolved: string };
      roof_triangulation: string;
    };
    timing_ms: {
      adapter_device_cpu_ms?: number;
      scene_build_cpu_ms: number;
      gpu_resource_apply_cpu_ms: number;
      renderer_init_cpu_ms: number;
    };
  };
  invalidate(): void;
  dispose(): void;
}>;
