import assert from 'node:assert/strict';
import {StaticCollisionLifecycleError,createStaticCollisionLifecycleState,applyStaticCollisionLifecycleEvent,STATIC_COLLISION_LIFECYCLE_SCHEMA,STATIC_COLLISION_LIFECYCLE_PHASE} from './static_collision_lifecycle_contract.mjs';
const A='a'.repeat(64), B='b'.repeat(64);
const frame={physicsFrameId:'physics:island-a',epoch:7};
let passed=0;
const base=()=>createStaticCollisionLifecycleState({worldFrameId:'world:nannestad',physicsFrameId:frame.physicsFrameId,physicsEpoch:frame.epoch});
const ev=(action,overrides={})=>({schema:STATIC_COLLISION_LIFECYCLE_SCHEMA,phase:STATIC_COLLISION_LIFECYCLE_PHASE,tick:120,action,collisionId:'terrain:center',tileId:'nannestad:618000:6690000:1000',artifactSha256:A,previousArtifactSha256:null,worldFrameId:'world:nannestad',physicsFrame:frame,dependentEntityIds:[],continuity:'none',...overrides});
function test(name,fn){fn();passed++;console.log(`PASS ${name}`)}
function code(c,fn){assert.throws(fn,e=>e instanceof StaticCollisionLifecycleError&&e.code===c)}
test('verified collision activates only in current post-maintenance physics epoch',()=>{const s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});assert.equal(s.collisions[0].artifactSha256,A)});
test('stale physics epoch fails closed before residency mutation',()=>code('PHYSICS_EPOCH_MISMATCH',()=>applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE',{physicsFrame:{...frame,epoch:6}}),currentPhysicsFrame:frame})));
test('render-origin leakage is rejected',()=>code('UNEXPECTED_FIELD',()=>applyStaticCollisionLifecycleEvent({state:base(),event:{...ev('ACTIVATE'),renderOriginEpoch:99},currentPhysicsFrame:frame})));
test('eviction is rejected while simulation entities depend on collision',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:['entity:b','entity:a']}),currentPhysicsFrame:frame});code('COLLISION_IN_USE',()=>applyStaticCollisionLifecycleEvent({state:s,event:ev('EVICT'),currentPhysicsFrame:frame}))});
test('dependency identities canonicalize deterministically',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:['entity:b','entity:a']}),currentPhysicsFrame:frame});assert.deepEqual(s.collisions[0].dependentEntityIds,['entity:a','entity:b'])});
test('in-use artifact replacement requires atomic continuity',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:['entity:a']}),currentPhysicsFrame:frame});code('CONTINUITY_REQUIRED',()=>applyStaticCollisionLifecycleEvent({state:s,event:ev('REPLACE',{artifactSha256:B,previousArtifactSha256:A,dependentEntityIds:['entity:a']}),currentPhysicsFrame:frame}))});
test('atomic replacement preserves residency without missing-collision intermediate state',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:['entity:a']}),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('REPLACE',{artifactSha256:B,previousArtifactSha256:A,dependentEntityIds:['entity:a'],continuity:'atomic-rebind'}),currentPhysicsFrame:frame});assert.equal(s.collisions.length,1);assert.equal(s.collisions[0].artifactSha256,B);assert.deepEqual(s.collisions[0].dependentEntityIds,['entity:a'])});
test('replacement must name exact previous artifact identity',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});code('PREVIOUS_ARTIFACT_MISMATCH',()=>applyStaticCollisionLifecycleEvent({state:s,event:ev('REPLACE',{artifactSha256:B,previousArtifactSha256:'c'.repeat(64),continuity:'atomic-rebind'}),currentPhysicsFrame:frame}))});
test('foreign tile replacement fails closed',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});code('TILE_ID_MISMATCH',()=>applyStaticCollisionLifecycleEvent({state:s,event:ev('REPLACE',{tileId:'nannestad:619000:6690000:1000',artifactSha256:B,previousArtifactSha256:A,continuity:'atomic-rebind'}),currentPhysicsFrame:frame}))});
test('eviction succeeds only after dependencies are explicitly released',()=>{let s=applyStaticCollisionLifecycleEvent({state:base(),event:ev('ACTIVATE'),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:['entity:a']}),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('SET_DEPENDENCIES',{dependentEntityIds:[]}),currentPhysicsFrame:frame});s=applyStaticCollisionLifecycleEvent({state:s,event:ev('EVICT'),currentPhysicsFrame:frame});assert.equal(s.collisions.length,0)});
console.log(JSON.stringify({status:'ATLAS_STATIC_COLLISION_LIFECYCLE_PASS',passed,total:10}));
